name: DVC Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.dvc'
      - '.dvc/**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc dvc[gdrive]

      - name: Verify Python and DVC installation
        run: |
          python --version
          pip show dvc

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Pull data with DVC
        env:
          DVC_GDRIVE_CREDENTIALS_FILE: ${{ github.workspace }}/gha-creds.json
        run: |
          # Rename the credentials file for DVC
          mv $(find $GITHUB_WORKSPACE -name "gha-creds-*.json") $DVC_GDRIVE_CREDENTIALS_FILE
          # Pull data
          dvc pull --no-run-cache -v

      - name: Debug file structure
        run: |
          ls -R my_project/src/

      - name: Check data statistics
        run: |
          python my_project/src/my_project/data.py > data_statistics.md
          echo '![](./mnist_images.png "MNIST images")' >> data_statistics.md
          echo '![](./train_label_distribution.png "Train label distribution")' >> data_statistics.md
          echo '![](./test_label_distribution.png "Test label distribution")' >> data_statistics.md

      - name: Setup cml
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create data_statistics.md --watermark-title="Data Checker"


