name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    - name: Set WANDB_API_KEY environment variable
      env:
        WANDB-API-KEY: ${{ secrets.WANDB-API-KEY }}
      run: echo "WANDB-API-KEY is set."

    - name: Set environment variables for macOS
      if: runner.os == 'macOS'
      run: |
        echo "PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0" >> $GITHUB_ENV

    - name: Test with pytest
      env: 
        WANDB-API-KEY: ${{ secrets.WANDB-API-KEY }}
      run: |
        pytest tests/test_data.py
        pytest tests/test_model.py
        pytest tests/test_training.py