name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    - name: Set WANDB_API_KEY environment variable
      run: |
        echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV

    - name: Set MPS Configuration (macOS only)
      if: runner.os == 'macOS'
      run: |
        echo "PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0" >> $GITHUB_ENV
        echo "PYTORCH_DISABLE_MPS=1" >> $GITHUB_ENV

    - name: Set PYTHONPATH for Windows (if OS is Windows)
      if: runner.os == 'Windows'
      run: echo "PYTHONPATH=${{ github.workspace }}\\src" >> $GITHUB_ENV

    # Add PYTHONPATH to include 'src' directory for the tests
    - name: Set PYTHONPATH
      if: runner.os != 'Windows'
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Test with pytest
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        pytest tests/test_data.py
        pytest tests/test_model.py
        pytest tests/test_training.py
